[package]
name = "rouge"
version = "0.1.0"
license = "GPL-3.0"
authors = ["Sebastian Andersson <sebastian@bittr.nu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
rltk="0.5.*"
specs = "0.15.*"
specs-derive = "0.4.*"
