[package]
name = "rouge"
version = "0.1.0"
license = "GPL-3.0"
authors = ["Sebastian Andersson <sebastian@bittr.nu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
bracket-lib = { version = "0.8.*", features = ["serde"] }
specs = { version = "0.15.*", features = ["serde"] }
specs-derive = "0.4.*"
serde= { version = "1.0.*", features = ["derive"] }
serde_json = "1.0.*"
serde_cbor = "*"
# glutin="0.22.0-alpha5"
