[package]
name = "rouge"
description = "A simple roguelike game"
repository = "https://github.com/bofh69/rouge/"
keywords = [ "game", "rougelike" ]
categories = [ "games" ]
version = "0.1.0"
license = "GPL-3.0"
authors = ["Sebastian Andersson <sebastian@bittr.nu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
bracket-lib = { path = "vendor/bracket-lib" }
legion = { path = "vendor/legion" }
# bracket-lib = "0.8.*"
# legion = "0.3.*"
