name: Build for release

on:
  repository_dispatch:
    types: [release-created]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12, windows-latest]
        include:
          - os: ubuntu-latest
            os_name: Ubuntu
            binary: rouge
          - os: macOS-12
            os_name: MacOS
            binary: rouge
          - os: windows-latest
            os_name: Windows
            binary: rouge.exe

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Build Release
      run: |
        cargo build --release --verbose

    - name: Upload release asset
      if: matrix.os != 'windows-latest'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.client_payload.upload_url }}
        asset_path: target/release/${{ matrix.binary }}
        asset_name: ${{ matrix.os_name }}-${{ matrix.binary }}
        asset_content_type: application/binary
