name: Rouge

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12, windows-latest]
        include:
          - os: ubuntu-latest
          - os: macOS-12
          - os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Build Release
      run: cargo build --verbose

    - name: Run tests
      if: matrix.os != 'windows-latest'
      run: cargo test --verbose

    - name: Check format
      if: matrix.os == 'ubuntu-latest'
      run: cargo fmt -- --check

    - name: Archive Windows artifacts
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: Windows Executable
        path: target/debug/rouge.exe

    - name: Archive MacOS artifacts
      if: matrix.os == 'macos-12'
      uses: actions/upload-artifact@v3
      with:
        name: MacOS Executable
        path: target/debug/rouge
